// <auto-generated />
namespace Friseur.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Sprint20221113 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Sprint20221113));
        
        string IMigrationMetadata.Id
        {
            get { return "202211252027015_Sprint2022.11.13"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
